# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='\u540d\u5b57')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u5934\u50cf')),
                ('introduce_title', models.CharField(max_length=100, verbose_name='\u4e2a\u4eba\u6807\u9898\u7b80\u4ecb')),
                ('motto', models.CharField(max_length=50, verbose_name='\u683c\u8a00')),
                ('introduce_p1', models.TextField(verbose_name='\u4e2a\u4eba\u7b80\u4ecb\u7b2c\u4e00\u6bb5')),
                ('introduce_p2', models.TextField(verbose_name='\u4e2a\u4eba\u7b80\u4ecb\u7b2c\u4e8c\u6bb5')),
                ('introduce_p3', models.TextField(verbose_name='\u4e2a\u4eba\u7b80\u4ecb\u7b2c\u4e09\u6bb5')),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u7b80\u4ecb',
                'verbose_name_plural': '\u4e2a\u4eba\u7b80\u4ecb',
            },
        ),
    ]
